### ISSUE TITLE
Dimension Error with running the option1 

### ISSUE THREAD

**Issue by msarguru** [jennasimit/flashfm#1]
Dear Developer,
I have been trying to finemap causal variants for two related traits following the steps mentioned in ### SNP correlation matrix and RAF vector provided - run single-trait and multi-trait fine-mapping

The locus is represented by 4 SNPs that shows significant association in both the trait 1 and trait 2
Have compiled the following variables

snpinfo
covY 
ybar (set to a vector of 0 for each of the trait) 
beta
N
raf
corX (for the SNPs mentioned in the snpinfo and beta file) 
Using rsIDs (and not as mentioned in the following note in the vignette)
_NOTE: SNP names must not contain ":" in FLASHFMwithJAM, JAMexpanded.multi, and JAMexpandedCor.multi.
So, if SNP names are in the form "19:45301088_T_C" change to "chr19_45301088_T_C"._ 

As I try to run the first step on single-trait mapping with the function FLASHFMwithJAM
The run goes through the iterations and crashes with the following error, 
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent

Debugging tells that the error takes place at the stage of the function JAMexpandedCor.multi

Is this known, any help or suggestions would be greatly appreciated.

Many thanks
M

**Comment by jennasimit** [comment]
Hello,

Thanks for your message and I'm sorry that you are getting this error. I have not come across this yet and was wondering if you could check that your beta is a list object, in the same format as the example beta object of flashfm; since you have two traits you will need: beta <- vector("list",2)
where beta[[i]] is a vector of SNP effects for trait i and names(beta[[i]]) is assigned the snp ids. 

If this doesn't help, could you please attach a screenshot or copy-paste all messages that appear when you run FLASHFMwithJAM? 

Thanks,
Jenn

**Comment by jennasimit** [comment]
Hello, 

Hope that it is running for you now. If still having an issue, please send a screenshot of all messages that appear when you run FLASHFMwithJAM to jennasimit@gmail.com and I will help you sort this out.

Best wishes,
Jenn

**Comment by msarguru** [comment]
Hi Jenn,

Thank you, I have followed up by email with the data and the sessioninfo. 

Many thanks for your inputs/suggestions

Regards
M

**Comment by jennasimit** [comment]
Thanks, I have responded by email. This was a data-related issue and should be fine once a region of SNPs is conctructed for your data. 

Closing this issue, but do let me know if more help is needed.

Jenn
